## Exceptions in Dart
Дартта ката шарттарын башкаруу жана каталарды башкаруу үчүн колдонулган механизмдер өзгөчөлүктөр болуп саналат. Өзгөчө кырдаалдар күтүлбөгөн жагдайлар же каталар пайда болгондо программанын нормалдуу агымын үзгүлтүккө учуратат жана программага катаны кантип чечүү керектигин аныктоого мүмкүндүк берет.

Дартта өзгөчө кырдаалдардын негизги механизми болуп аракет кылуу блоктору саналат. Аткарылуучу код try блогунун ичинде жайгаштырылат, ал эми catch блогу мүмкүн болгон каталарды кармоо жана иштетүү үчүн колдонулат.

Бул жерде бир мисал:
```dart
void main() {
  try {
    // Code that may cause a potential error
    int result = 10 ~/ 0; // Division operation that will cause an error
    print('Result: $result');
  } catch (e) {
    // Actions to take when an error is caught
    print('Error: $e');
  }
}

```
Жогорудагы мисалда нөл катага бөлүү (IntegerDivisionByZeroException) бөлүү операциясы учурунда пайда болот. Бул ката кармоо блогунда кармалып, экранга "Ката: [ката билдирүү]" билдирүүсү басылып чыгат.

Кармап алуу блогу өзгөчө өзгөчөлүктөргө ылайыкташтырылышы мүмкүн. Эгер сиз катанын белгилүү бир түрүн кармагыңыз келсе, анда ал түрүн catch блогунда көрсөтсөңүз болот.
```dart
void main() {
  try {
    // Code that may cause a potential error
    int result = 10 ~/ 0; // Division operation that will cause an error
    print('Result: $result');
  } on IntegerDivisionByZeroException {
    // Catch only the division by zero error
    print('Division by zero error!');
  } catch (e) {
    // General error message for other errors
    print('Error: $e');
  }
}
```
Жогорудагы мисалда нөл катага бөлүү (IntegerDivisionByZeroException) бөлүү операциясы учурунда пайда болот. Бул ката кармоо блогунда кармалып, экранга "Ката: [ката билдирүү]" билдирүүсү басылып чыгат.

Кармап алуу блогу өзгөчө өзгөчөлүктөргө ылайыкташтырылышы мүмкүн. Эгер сиз катанын белгилүү бир түрүн кармагыңыз келсе, анда ал түрүн catch блогунда көрсөтсөңүз болот.
```dart
void main() {
  try {
    // Code that may cause a potential error
    int result = 10 ~/ 0; // Division operation that will cause an error
    print('Result: $result');
  } on IntegerDivisionByZeroException {
    // Catch only the division by zero error
    print('Division by zero error!');
  } catch (e) {
    // General error message for other errors
    print('Error: $e');
  }
}

```
Жогорудагы мисалда, бир гана IntegerDivisionByZeroException түрүндөгү каталар on ачкыч сөзү менен кармалып, нөл каталарга бөлүү үчүн белгилүү бир билдирүү басылып чыгат. Башка каталар үчүн жалпы ката билдирүүсү менен жалпы кармоо блогу колдонулат.

Try-catch блокторунан тышкары, өзгөчө учурларды тазалоо операциялары жана ресурстарды чыгаруу үчүн акыркы блок менен да колдонсо болот.
```dart
void main() {
  try {
    // Code that may cause a potential error
    int result = 10 ~/ 0; // Division operation that will cause an error
    print('Result: $result');
  } catch (e) {
    // Actions to take when an error is caught
    print('Error: $e');
  } finally {
    // Cleanup operations or resource release
    print('Cleanup operations');
  }
}

```
Жогорудагы мисалда, finally блогу ката пайда болгон-болбогонуна карабастан аткарылышы керек болгон тазалоо операциялары үчүн колдонулат.

Өзгөчө кырдаалдар дарттагы каталарды иштетүүнүн маанилүү бөлүгү болуп саналат, бул күтүлбөгөн кырдаалдарды кылдаттык менен чечүүгө жана тийиштүү ката билдирүүлөрүн же калыбына келтирүү механизмдерин камсыз кылууга мүмкүндүк берет.